<a href="https://colab.research.google.com/github/parthpuwar/DataScienceexperiment/blob/main/Reindexing%2Bimage_Proc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Now we'll elarn about reindexing

In [2]:
import numpy as np
from pandas import Series, DataFrame
import pandas as pd
from numpy.random import randn

In [3]:
#Lets create a new series
ser1 = Series([1,2,3,4],index=['A','B','C','D'])

In [4]:
#Show
ser1

A    1
B    2
C    3
D    4
dtype: int64

In [5]:
#Call reindex to rearrange the data to a new index
ser2 = ser1.reindex(['A','B','C','D','E','F'])

In [6]:
#Show
ser2

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
dtype: float64

In [7]:
# We can alos fill in values for new indexes
ser2.reindex(['A','B','C','D','E','F','G'],fill_value=0)

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
F    NaN
G    0.0
dtype: float64

In [8]:
#Using a particular method for filling values
ser3 = Series(['USA','Mexico','Canada'],index=[0,5,10])

#Show
ser3

0        USA
5     Mexico
10    Canada
dtype: object

In [9]:
#Can use a forward fill for interploating values vetween indices
ser3.reindex(range(15),method='ffill')

0        USA
1        USA
2        USA
3        USA
4        USA
5     Mexico
6     Mexico
7     Mexico
8     Mexico
9     Mexico
10    Canada
11    Canada
12    Canada
13    Canada
14    Canada
dtype: object

In [10]:
#Reindexing rows, columns or both

#Lets make a datafram ewith some random values
dframe = DataFrame(randn(25).reshape((5,5)),index=['A','B','D','E','F'],columns=['col1','col2','col3','col4','col5'])

#Show
dframe

       col1      col2      col3      col4      col5
A  0.899450  0.532347  1.142392  1.247678  0.737959
B  0.365626 -1.763782  0.398378  1.644820  0.717133
D -1.759850  0.670131 -0.189135 -0.237095  0.134213
E -0.504697 -0.301948 -0.522703  0.101439  0.422822
F  0.249482 -0.539054 -0.807600 -1.248061  0.124547

In [11]:
#Notice we forgot 'C' , lets reindex it into dframe
dframe2 = dframe.reindex(['A','B','C','D','E','F'])

In [12]:
#Can also explicitly reindex columns
new_columns = ['col1','col2','col3','col4','col5','col6']

dframe2.reindex(columns=new_columns)

       col1      col2      col3      col4      col5  col6
A  0.899450  0.532347  1.142392  1.247678  0.737959   NaN
B  0.365626 -1.763782  0.398378  1.644820  0.717133   NaN
C       NaN       NaN       NaN       NaN       NaN   NaN
D -1.759850  0.670131 -0.189135 -0.237095  0.134213   NaN
E -0.504697 -0.301948 -0.522703  0.101439  0.422822   NaN
F  0.249482 -0.539054 -0.807600 -1.248061  0.124547   NaN

In [13]:
#Reindex quickly using the label-indexing with ix (we'll see this more in the future)

#Show original
dframe

       col1      col2      col3      col4      col5
A  0.899450  0.532347  1.142392  1.247678  0.737959
B  0.365626 -1.763782  0.398378  1.644820  0.717133
D -1.759850  0.670131 -0.189135 -0.237095  0.134213
E -0.504697 -0.301948 -0.522703  0.101439  0.422822
F  0.249482 -0.539054 -0.807600 -1.248061  0.124547

In [14]:
dframe.ix[['A','B','C','D','E','F'],new_columns]

AttributeError: 'DataFrame' object has no attribute 'ix'

In [15]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

# Load the image
img = Image.open("Shiva wallpaper Enhanced.png").convert("L")

# Make it small
#img = img.resize((60, 80))

# Convert image → NumPy array
arr = np.array(img)

print(arr.shape)
print(arr)

# Convert NumPy array → image
plt.imshow(arr, cmap="gray")
plt.axis("off")
plt.show()

FileNotFoundError: [Errno 2] No such file or directory: 'Shiva wallpaper Enhanced.png'

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image

In [ ]:
img = Image.open("Shiva wallpaper Enhanced.png").convert("L")

In [ ]:
arr = np.array(img)

In [ ]:
arr1=arr*255

In [ ]:
print(arr.shape)

In [ ]:
print(arr)

In [ ]:
plt.imshow(arr1, cmap="GnBu")